### ISSUE TITLE
Skip GitHub Code Frame

### ISSUE THREAD

**Issue by KevinZonda** [itorr/bionic-reading.user.js#10]
![image](https://user-images.githubusercontent.com/33132228/169626482-5d86bebf-ae9a-46d8-b5b9-5415f44d1ae9.png)

It would be pretty nice if can skipped the code part

**Comment by itorr** [comment]
Thank you for your proposal, Now supported
https://github.com/itorr/bionic-reading.user.js/commit/0aae0bf9757b9c5b54bc6ac00d57c1d2d9da1128
