### ISSUE TITLE
[功能] 能否忽略缩略词、非句首字母大写加粗

### ISSUE THREAD

**Issue by DoudouMee** [itorr/bionic-reading.user.js#11]
我觉得可以对其中的缩略词或含有缩略的词
以及句中的大写字母

例如“ST” “LPCLink” “IDEs” “OpenOCD”等不加粗

![image](https://user-images.githubusercontent.com/43898894/169636739-68a0d736-5bc2-4147-a16b-64c048296666.png)

个人认为对缩略词的判定可以是连续两个大写字母

此外，这一段话看起来杂乱的原因可能还在于加粗过多
官方的似乎能调整加粗频率和透明度，“Saccade” “Opacity”
不知道实现容不容易实现

**Comment by itorr** [comment]
确实 我觉得前半高亮匹配规则可以调整到 ‘/[a-Z][a-z]{0,}/‘ 

i a 等一字节长度的单词 以及缩略词、以及驼峰单词的高亮细节还要再确定下





> 此外，这一段话看起来杂乱的原因可能还在于加粗过多 官方的似乎能调整加粗频率和透明度，“Saccade” “Opacity” 不知道实现容不容易实现

Saccade 、Opacity 这两个概念我还没理解，具体可以影响哪些细节？

**Comment by DoudouMee** [comment]
Saccade 和 Opacity是官网上提到的。看它给的示例，我的理解是分别影响加粗的频率和透明度。调整Saccade实现有间隔or跳跃地加粗，这样不对每个单词都做处理，不会显得拥挤；Opacity就是调整了显示效果，加粗程度，调整Opacity让加粗文字看起来不那么明显or刺眼


另外官网还提供API，免费版每天500次请求，不知道能否利用上

**Comment by itorr** [comment]
> Saccade 和 Opacity是官网上提到的。看它给的示例，我的理解是分别影响加粗的频率和透明度。调整Saccade实现有间隔or跳跃地加粗，这样不对每个单词都做处理，不会显得拥挤；Opacity就是调整了显示效果，加粗程度，调整Opacity让加粗文字看起来不那么明显or刺眼 另外官网还提供API，免费版每天500次请求，不知道能否利用上

理解了，需要在添加自定义选项窗口后支持，Opacity 确实低一点更舒服

**Comment by itorr** [comment]
忽略略缩词合并到 https://github.com/itorr/bionic-reading.user.js/issues/7
Saccade 、Opacity 功能新开 https://github.com/itorr/bionic-reading.user.js/issues/22
