### ISSUE TITLE
减少对长单词的加粗数量

### ISSUE THREAD

**Issue by chinoll** [itorr/bionic-reading.user.js#12]
只加粗前3-4个字母效果会好一些？
![image](https://user-images.githubusercontent.com/22575232/169638303-95d2a4f5-285b-40e0-8d36-d6299b4bff54.png)

**Comment by itorr** [comment]
添加了选项，现在可以设置最长加粗长度了 https://github.com/itorr/bionic-reading.user.js#%E9%80%89%E9%A1%B9
