### ISSUE TITLE
忽略 URL

### ISSUE THREAD

**Issue by 8Q757** [itorr/bionic-reading.user.js#13]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/28482172/169641329-5cc6586b-7800-4ca8-b9bb-f8a277348360.png">

**Comment by itorr** [comment]
我觉得一个合格的 URL 是需要有足够的描述词描述资源内容的，考虑在加入自定义设置时添加对应选项

**Comment by itorr** [comment]
添加了跳过 URL 的选项，开启后会跳过 `/^https?:\/\//` 开头的链接元素
https://github.com/itorr/bionic-reading.user.js/commit/317f5db596e9a9f11e38dcd774a9d10fa7601bdb
