### ISSUE TITLE
是否可添加快捷键以应用脚本？

### ISSUE THREAD

**Issue by chNg1o** [itorr/bionic-reading.user.js#14]
Ctrl＋什么键就应用

**Comment by itorr** [comment]
先 [添加 Ctrl + B / ⌘ + B 复原、重做快捷键](https://github.com/itorr/bionic-reading.user.js/commit/15f58022063e11c1ce434a7e54e58553e476d9cf)

https://github.com/itorr/bionic-reading.user.js/commit/15f58022063e11c1ce434a7e54e58553e476d9cf

**Comment by itorr** [comment]
是否默认开启待考
