### ISSUE TITLE
打开脚本后原先可以点击的链接英文单词无法点击

### ISSUE THREAD

**Issue by ironald** [itorr/bionic-reading.user.js#15]
比如，https://arxiv.org/

**Comment by xfdj** [comment]
同样的问题出现在https://www.tampermonkey.net/scripts.php

**Comment by itorr** [comment]
尝试修复了，可以更新脚本试试

**Comment by xfdj** [comment]
尝试了一下，目前浏览到的网站的问题都解决了

**Comment by ironald** [comment]
感谢解决，希望这次能坚持下来，每天读点英语



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月23日(周一) 下午4:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [itorr/bionic-reading.user.js] 打开脚本后原先可以点击的链接英文单词无法点击 (Issue #15)




 
尝试了一下，目前浏览到的网站的问题都解决了
