### ISSUE TITLE
Will break CF's Analysis Word

### ISSUE THREAD

**Issue by KevinZonda** [itorr/bionic-reading.user.js#17]
After:
![image](https://user-images.githubusercontent.com/33132228/169667821-a3e90ed9-6c19-4425-8864-8e9f6d41f6f2.png)

**Comment by KevinZonda** [comment]
Previous:
![image](https://user-images.githubusercontent.com/33132228/169667826-049ecec4-1fdb-4cc6-9a39-d85e34f0fba2.png)

**Comment by itorr** [comment]
感谢反馈，现在应该已经修复了
