### ISSUE TITLE
能否增加 黑暗模式（黑底白字）下，字母加粗同时能更换为其他颜色的功能？

### ISSUE THREAD

**Issue by alexiao76** [itorr/bionic-reading.user.js#21]
黑底白字仅仅靠加粗的highlight效果明显不如白底黑字 但是夜间看白底黑色眼睛受不了

**Comment by itorr** [comment]
这个脚本来做改色感觉有些不太适合，这个脚本的功能应该仅仅是 Bionic-Reading ？
