### ISSUE TITLE
在notion页面会和输入冲突

### ISSUE THREAD

**Issue by sevelee** [itorr/bionic-reading.user.js#23]
![Honeycam 2022-05-24 15-00-36](https://user-images.githubusercontent.com/8036235/169968694-21894f8e-d5dd-4e69-b234-8d47bf478605.gif)
如图，光标会一直跑到最前面去

**Comment by yankai-wang** [comment]
Gmail 输入同样出现此问题。

**Comment by itorr** [comment]
现在默认跳过可编辑元素，应该解决了这个问题
