### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by laike9m** [itorr/bionic-reading.user.js#4]
想问一下是否有打算发布扩展版本呢？如果有的话，希望能支持黑白名单功能，以便在特定网站启用/禁用 bionic reading。

**Comment by itorr** [comment]
![image](https://user-images.githubusercontent.com/1933673/169507666-fe597e3a-919e-4b81-9467-551d4a7acf62.png)
暂时不打算开发浏览器扩展版本，油猴脚本一般也都可以很方便的设置黑名单

**Comment by laike9m** [comment]
了解。主要是公司不让用油猴。或许我可以自己写一个
