### ISSUE TITLE
Could cause greasyfork.org 404/可能会导致 greasyfork.org 404

### ISSUE THREAD

**Issue by KevinZonda** [itorr/bionic-reading.user.js#9]
Hi, first of all I would like to thank you for your brilliant work. I have installed the plugin and it works perfectly. However, I found that when I tried to install a new plugin on greasyfork.org it always returned a 404, after disabling the extension this problem was solved.

你好，首先要感谢你的出色工作。我已经安装了这个插件，它工作得非常好。但我发现，当我试图在greasyfork.org上安装新的插件时，它总是返回404，在禁用该扩展后，这个问题就解决了。

**Comment by KevinZonda** [comment]
Seems only on English model can cause such issue

**Comment by itorr** [comment]
Thank you for your feedback. it's bug. It should have been fixed at present. can update it and have a try
https://github.com/itorr/bionic-reading.user.js/commit/c9b71b6fb4c6769ad5b8558b3e70ca5b91c1f8c3
